server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka,http://eureka2:7002/eureka
    fetch-registry: true
    register-with-eureka: false

feign:
  hystrix:
    enabled: true
