server:
  port: 7001

eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2:7002/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 2000