spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: welcome1
logging:
  level:
    org.springframework.security: info
