server:
  port: 9001

spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: nacos01:8848,nacos02:8848,nacos03:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'
# 当前版本下，该属性的默认值为false，需要修改为true
feign:
  sentinel:
    enabled: true
